### ISSUE TITLE
grant and user group for user at user page

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji_sass#19]
1. grant for user group does not show at user page
2. the position of user group should be left aligned

![usergroup_user_grant](https://cloud.githubusercontent.com/assets/4938318/4559779/50e763e0-4eef-11e4-95a7-62be814170e7.png)
![user_grant_usergroup](https://cloud.githubusercontent.com/assets/4938318/4559778/50e4ae84-4eef-11e4-83c6-11038e532a49.png)
![user_grant_usergroup2](https://cloud.githubusercontent.com/assets/4938318/4559780/50eba612-4eef-11e4-9b84-e52220590bbb.PNG)

**Comment by schlender** [comment]
can't reproduce


please cross-check
