### ISSUE TITLE
position of remove button in admin configuration

### ISSUE THREAD

**Issue by yaoyan** [imeji-community/imeji_sass#20]
in english and japanese

Firefox
![removebutton_configuration](https://cloud.githubusercontent.com/assets/4938318/4561221/145e4694-4efb-11e4-901f-afb7bcbf1d02.png)

IE
![removebutton_configuration_ie10](https://cloud.githubusercontent.com/assets/4938318/4561220/1450e4fe-4efb-11e4-9e5c-8fd6720596a7.PNG)

**Comment by schlender** [comment]
currently: text is replaced with icons

**Comment by schlender** [comment]
fixed
